//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAZYSHELL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadNotes {
            get {
                return ((bool)(this["LoadNotes"]));
            }
            set {
                this["LoadNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\\\\"")]
        public string LastRomPath {
            get {
                return ((string)(this["LastRomPath"]));
            }
            set {
                this["LastRomPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VisualThemeSystem {
            get {
                return ((bool)(this["VisualThemeSystem"]));
            }
            set {
                this["VisualThemeSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int UndoStackSize {
            get {
                return ((int)(this["UndoStackSize"]));
            }
            set {
                this["UndoStackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://home.comcast.net/~giangurgolo/patches/")]
        public string patchServerURL {
            get {
                return ((string)(this["patchServerURL"]));
            }
            set {
                this["patchServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NotePathCustom {
            get {
                return ((string)(this["NotePathCustom"]));
            }
            set {
                this["NotePathCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection LevelNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LevelNames"]));
            }
            set {
                this["LevelNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZSNESPath {
            get {
                return ((string)(this["ZSNESPath"]));
            }
            set {
                this["ZSNESPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-m -zs 0 -v 2")]
        public string PreviewArguments {
            get {
                return ((string)(this["PreviewArguments"]));
            }
            set {
                this["PreviewArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewFirstTime {
            get {
                return ((bool)(this["PreviewFirstTime"]));
            }
            set {
                this["PreviewFirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewDynamicRomName {
            get {
                return ((bool)(this["PreviewDynamicRomName"]));
            }
            set {
                this["PreviewDynamicRomName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-m -zs 0 -v 2")]
        public string PreviewArgsDefault {
            get {
                return ((string)(this["PreviewArgsDefault"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UnverifiedRomWarning {
            get {
                return ((bool)(this["UnverifiedRomWarning"]));
            }
            set {
                this["UnverifiedRomWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEncryptionWarnings {
            get {
                return ((bool)(this["ShowEncryptionWarnings"]));
            }
            set {
                this["ShowEncryptionWarnings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\\\\"")]
        public string LastDirectory {
            get {
                return ((string)(this["LastDirectory"]));
            }
            set {
                this["LastDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadLastUsedROM {
            get {
                return ((bool)(this["LoadLastUsedROM"]));
            }
            set {
                this["LoadLastUsedROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Mushroom Kingdom</string>
  <string>Rose Town Items</string>
  <string>Rose Town Armor</string>
  <string>Frog Disciple Shop</string>
  <string>Moleville Shop</string>
  <string>Marrymore Shop</string>
  <string>Frog Coin Emporium</string>
  <string>Sea Item shop</string>
  <string>Seaside Town Items (pre-Yaridovich)</string>
  <string>Juice Bar (no card)</string>
  <string>Juice Bar (alto card)</string>
  <string>Juice Bar (tenor card)</string>
  <string>Juice Bar (soprano card)</string>
  <string>Seaside Weapons</string>
  <string>Seaside Armor</string>
  <string>Seaside Accessory</string>
  <string>Seaside Health Foods</string>
  <string>Monstro Town shop</string>
  <string>Nimbus Land shop</string>
  <string>Hinopio's Shop</string>
  <string>Baby Goomba shop</string>
  <string>Nimbus Land Item/Weapon</string>
  <string>Croco's Shop 1</string>
  <string>Croco's Shop 2</string>
  <string>Toad's Shop</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
  <string>___DUMMY</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ShopNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ShopNames"]));
            }
            set {
                this["ShopNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection EventLabels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EventLabels"]));
            }
            set {
                this["EventLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ActionLabels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActionLabels"]));
            }
            set {
                this["ActionLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <str" +
            "ing />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  " +
            "<string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />" +
            "\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>!</string>\r\n" +
            "  <string>“</string>\r\n  <string>”</string>\r\n  <string />\r\n  <string />\r\n  <strin" +
            "g>‘</string>\r\n  <string>’</string>\r\n  <string>(</string>\r\n  <string>)</string>\r\n" +
            "  <string />\r\n  <string />\r\n  <string>,</string>\r\n  <string>-</string>\r\n  <strin" +
            "g>.</string>\r\n  <string>/</string>\r\n  <string>0</string>\r\n  <string>1</string>\r\n" +
            "  <string>2</string>\r\n  <string>3</string>\r\n  <string>4</string>\r\n  <string>5</s" +
            "tring>\r\n  <string>6</string>\r\n  <string>7</string>\r\n  <string>8</string>\r\n  <str" +
            "ing>9</string>\r\n  <string>~</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string>?</string>\r\n  <string>@</string>\r\n  <string>A</string>\r\n" +
            "  <string>B</string>\r\n  <string>C</string>\r\n  <string>D</string>\r\n  <string>E</s" +
            "tring>\r\n  <string>F</string>\r\n  <string>G</string>\r\n  <string>H</string>\r\n  <str" +
            "ing>I</string>\r\n  <string>J</string>\r\n  <string>K</string>\r\n  <string>L</string>" +
            "\r\n  <string>M</string>\r\n  <string>N</string>\r\n  <string>O</string>\r\n  <string>P<" +
            "/string>\r\n  <string>Q</string>\r\n  <string>R</string>\r\n  <string>S</string>\r\n  <s" +
            "tring>T</string>\r\n  <string>U</string>\r\n  <string>V</string>\r\n  <string>W</strin" +
            "g>\r\n  <string>X</string>\r\n  <string>Y</string>\r\n  <string>Z</string>\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <str" +
            "ing>a</string>\r\n  <string>b</string>\r\n  <string>c</string>\r\n  <string>d</string>" +
            "\r\n  <string>e</string>\r\n  <string>f</string>\r\n  <string>g</string>\r\n  <string>h<" +
            "/string>\r\n  <string>i</string>\r\n  <string>j</string>\r\n  <string>k</string>\r\n  <s" +
            "tring>l</string>\r\n  <string>m</string>\r\n  <string>n</string>\r\n  <string>o</strin" +
            "g>\r\n  <string>p</string>\r\n  <string>q</string>\r\n  <string>r</string>\r\n  <string>" +
            "s</string>\r\n  <string>t</string>\r\n  <string>u</string>\r\n  <string>v</string>\r\n  " +
            "<string>w</string>\r\n  <string>x</string>\r\n  <string>y</string>\r\n  <string>z</str" +
            "ing>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string>:</string>\r\n  <string>;</string>\r\n  <s" +
            "tring>&lt;</string>\r\n  <string>&gt;</string>\r\n  <string />\r\n  <string>#</string>" +
            "\r\n  <string>+</string>\r\n  <string>×</string>\r\n  <string>%</string>\r\n  <string />" +
            "\r\n  <string />\r\n  <string />\r\n  <string>*</string>\r\n  <string>\'</string>\r\n  <str" +
            "ing>&amp;</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Keystrokes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Keystrokes"]));
            }
            set {
                this["Keystrokes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateBackupROM {
            get {
                return ((bool)(this["CreateBackupROM"]));
            }
            set {
                this["CreateBackupROM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateBackupROMSave {
            get {
                return ((bool)(this["CreateBackupROMSave"]));
            }
            set {
                this["CreateBackupROMSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupROMDirectory {
            get {
                return ((string)(this["BackupROMDirectory"]));
            }
            set {
                this["BackupROMDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <str" +
            "ing />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  " +
            "<string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />" +
            "\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <strin" +
            "g />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string>.</string>\r\n  <string>:</string>\r\n  <string>,<" +
            "/string>\r\n  <string />\r\n  <string>.</string>\r\n  <string>/</string>\r\n  <string>0<" +
            "/string>\r\n  <string>1</string>\r\n  <string>2</string>\r\n  <string>3</string>\r\n  <s" +
            "tring>4</string>\r\n  <string>5</string>\r\n  <string>6</string>\r\n  <string>7</strin" +
            "g>\r\n  <string>8</string>\r\n  <string>9</string>\r\n  <string>~</string>\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>?</string>\r\n  <string />" +
            "\r\n  <string>A</string>\r\n  <string>B</string>\r\n  <string>C</string>\r\n  <string>D<" +
            "/string>\r\n  <string>E</string>\r\n  <string>F</string>\r\n  <string>G</string>\r\n  <s" +
            "tring>H</string>\r\n  <string>I</string>\r\n  <string>J</string>\r\n  <string>K</strin" +
            "g>\r\n  <string>L</string>\r\n  <string>M</string>\r\n  <string>N</string>\r\n  <string>" +
            "O</string>\r\n  <string>P</string>\r\n  <string>Q</string>\r\n  <string>R</string>\r\n  " +
            "<string>S</string>\r\n  <string>T</string>\r\n  <string>U</string>\r\n  <string>V</str" +
            "ing>\r\n  <string>W</string>\r\n  <string>X</string>\r\n  <string>Y</string>\r\n  <strin" +
            "g>Z</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string>a</string>\r\n  <string>b</string>\r\n  <string>c</strin" +
            "g>\r\n  <string>d</string>\r\n  <string>e</string>\r\n  <string>f</string>\r\n  <string>" +
            "g</string>\r\n  <string>h</string>\r\n  <string>i</string>\r\n  <string>j</string>\r\n  " +
            "<string>k</string>\r\n  <string>l</string>\r\n  <string>m</string>\r\n  <string>n</str" +
            "ing>\r\n  <string>o</string>\r\n  <string>p</string>\r\n  <string>q</string>\r\n  <strin" +
            "g>r</string>\r\n  <string>s</string>\r\n  <string>t</string>\r\n  <string>u</string>\r\n" +
            "  <string>v</string>\r\n  <string>w</string>\r\n  <string>x</string>\r\n  <string>y</s" +
            "tring>\r\n  <string>z</string>\r\n  <string>!</string>\r\n  <string>#</string>\r\n  <str" +
            "ing>-</string>\r\n  <string>’</string>\r\n  <string />\r\n  <string>:</string>\r\n  <str" +
            "ing>.</string>\r\n  <string>“</string>\r\n  <string>”</string>\r\n  <string />\r\n  <str" +
            "ing />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  " +
            "<string />\r\n  <string />\r\n  <string />\r\n  <string>:</string>\r\n  <string>;</strin" +
            "g>\r\n  <string>&lt;</string>\r\n  <string>&gt;</string>\r\n  <string />\r\n  <string>#<" +
            "/string>\r\n  <string>+</string>\r\n  <string>×</string>\r\n  <string>%</string>\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string />\r\n  <string>*</string>\r\n  <string>\'</string>" +
            "\r\n  <string />\r\n  <string />\r\n  <string />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KeystrokesMenu {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeystrokesMenu"]));
            }
            set {
                this["KeystrokesMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <str" +
            "ing />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  " +
            "<string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />" +
            "\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>!</string>\r\n" +
            "  <string>“</string>\r\n  <string>”</string>\r\n  <string />\r\n  <string />\r\n  <strin" +
            "g>‘</string>\r\n  <string>’</string>\r\n  <string>(</string>\r\n  <string>)</string>\r\n" +
            "  <string />\r\n  <string />\r\n  <string>,</string>\r\n  <string>-</string>\r\n  <strin" +
            "g>.</string>\r\n  <string>/</string>\r\n  <string>0</string>\r\n  <string>1</string>\r\n" +
            "  <string>2</string>\r\n  <string>3</string>\r\n  <string>4</string>\r\n  <string>5</s" +
            "tring>\r\n  <string>6</string>\r\n  <string>7</string>\r\n  <string>8</string>\r\n  <str" +
            "ing>9</string>\r\n  <string>~</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n" +
            "  <string />\r\n  <string>?</string>\r\n  <string />\r\n  <string>A</string>\r\n  <strin" +
            "g>B</string>\r\n  <string>C</string>\r\n  <string>D</string>\r\n  <string>E</string>\r\n" +
            "  <string>F</string>\r\n  <string>G</string>\r\n  <string>H</string>\r\n  <string>I</s" +
            "tring>\r\n  <string>J</string>\r\n  <string>K</string>\r\n  <string>L</string>\r\n  <str" +
            "ing>M</string>\r\n  <string>N</string>\r\n  <string>O</string>\r\n  <string>P</string>" +
            "\r\n  <string>Q</string>\r\n  <string>R</string>\r\n  <string>S</string>\r\n  <string>T<" +
            "/string>\r\n  <string>U</string>\r\n  <string>V</string>\r\n  <string>W</string>\r\n  <s" +
            "tring>X</string>\r\n  <string>Y</string>\r\n  <string>Z</string>\r\n  <string />\r\n  <s" +
            "tring />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string>a</s" +
            "tring>\r\n  <string>b</string>\r\n  <string>c</string>\r\n  <string>d</string>\r\n  <str" +
            "ing>e</string>\r\n  <string>f</string>\r\n  <string>g</string>\r\n  <string>h</string>" +
            "\r\n  <string>i</string>\r\n  <string>j</string>\r\n  <string>k</string>\r\n  <string>l<" +
            "/string>\r\n  <string>m</string>\r\n  <string>n</string>\r\n  <string>o</string>\r\n  <s" +
            "tring>p</string>\r\n  <string>q</string>\r\n  <string>r</string>\r\n  <string>s</strin" +
            "g>\r\n  <string>t</string>\r\n  <string>u</string>\r\n  <string>v</string>\r\n  <string>" +
            "w</string>\r\n  <string>x</string>\r\n  <string>y</string>\r\n  <string>z</string>\r\n  " +
            "<string />\r\n  <string />\r\n  <string>-</string>\r\n  <string>’</string>\r\n  <string " +
            "/>\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <str" +
            "ing />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  " +
            "<string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />" +
            "\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <strin" +
            "g />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <string />\r\n  <s" +
            "tring>&amp;</string>\r\n  <string />\r\n  <string />\r\n  <string />\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection KeystrokesDesc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeystrokesDesc"]));
            }
            set {
                this["KeystrokesDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadAllData {
            get {
                return ((bool)(this["LoadAllData"]));
            }
            set {
                this["LoadAllData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewMaxStats {
            get {
                return ((bool)(this["PreviewMaxStats"]));
            }
            set {
                this["PreviewMaxStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte PreviewAllies {
            get {
                return ((byte)(this["PreviewAllies"]));
            }
            set {
                this["PreviewAllies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PreviewBattlefield {
            get {
                return ((int)(this["PreviewBattlefield"]));
            }
            set {
                this["PreviewBattlefield"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastLevel {
            get {
                return ((int)(this["LastLevel"]));
            }
            set {
                this["LastLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PreviewLevel {
            get {
                return ((int)(this["PreviewLevel"]));
            }
            set {
                this["PreviewLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF")]
        public string AllyEquipment {
            get {
                return ((string)(this["AllyEquipment"]));
            }
            set {
                this["AllyEquipment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string History {
            get {
                return ((string)(this["History"]));
            }
            set {
                this["History"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSprite {
            get {
                return ((int)(this["LastSprite"]));
            }
            set {
                this["LastSprite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastDialogue {
            get {
                return ((int)(this["LastDialogue"]));
            }
            set {
                this["LastDialogue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastEventScript {
            get {
                return ((int)(this["LastEventScript"]));
            }
            set {
                this["LastEventScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastEffect {
            get {
                return ((int)(this["LastEffect"]));
            }
            set {
                this["LastEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastFormation {
            get {
                return ((int)(this["LastFormation"]));
            }
            set {
                this["LastFormation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastMonster {
            get {
                return ((int)(this["LastMonster"]));
            }
            set {
                this["LastMonster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastItem {
            get {
                return ((int)(this["LastItem"]));
            }
            set {
                this["LastItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastAttack {
            get {
                return ((int)(this["LastAttack"]));
            }
            set {
                this["LastAttack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSpell {
            get {
                return ((int)(this["LastSpell"]));
            }
            set {
                this["LastSpell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastAnimation {
            get {
                return ((int)(this["LastAnimation"]));
            }
            set {
                this["LastAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastAnimationCat {
            get {
                return ((int)(this["LastAnimationCat"]));
            }
            set {
                this["LastAnimationCat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastEventScriptCat {
            get {
                return ((int)(this["LastEventScriptCat"]));
            }
            set {
                this["LastEventScriptCat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastBattlefield {
            get {
                return ((int)(this["LastBattlefield"]));
            }
            set {
                this["LastBattlefield"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastBattleDialogue {
            get {
                return ((int)(this["LastBattleDialogue"]));
            }
            set {
                this["LastBattleDialogue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastFormationPack {
            get {
                return ((int)(this["LastFormationPack"]));
            }
            set {
                this["LastFormationPack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastAudioSample {
            get {
                return ((int)(this["LastAudioSample"]));
            }
            set {
                this["LastAudioSample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RememberLastIndex {
            get {
                return ((bool)(this["RememberLastIndex"]));
            }
            set {
                this["RememberLastIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstLoad {
            get {
                return ((bool)(this["FirstLoad"]));
            }
            set {
                this["FirstLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastMineCart {
            get {
                return ((int)(this["LastMineCart"]));
            }
            set {
                this["LastMineCart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>G</string>
  <string>H</string>
  <string>E</string>
  <string>F</string>
  <string>C</string>
  <string>D</string>
  <string>A</string>
  <string>B</string>
  <string>I</string>
  <string>J</string>
  <string>K</string>
  <string>L</string>
  <string>M</string>
  <string>N</string>
  <string>O</string>
  <string>P</string>
  <string>W</string>
  <string>X</string>
  <string>U</string>
  <string>V</string>
  <string>S</string>
  <string>T</string>
  <string>Q</string>
  <string>R</string>
  <string>Y</string>
  <string>Z</string>
  <string>!</string>
  <string>?</string>
  <string>.</string>
  <string>*</string>
  <string>@</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection KeystrokesBonus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KeystrokesBonus"]));
            }
            set {
                this["KeystrokesBonus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSPC {
            get {
                return ((int)(this["LastSPC"]));
            }
            set {
                this["LastSPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSoundType {
            get {
                return ((int)(this["LastSoundType"]));
            }
            set {
                this["LastSoundType"] = value;
            }
        }
    }
}
